# This is a taskctl's tasks configuration file.
# More information at https://github.com/taskctl/taskctl
pipelines:
  start:
    - task: install
    - task: build
      depends_on: install
    - task: start
      depends_on: build
  
  publish:
    - task: install
    - task: build
      depends_on: install
    - task: publish
      depends_on: build
  
tasks:
  install:
    command:
      - npm install
      - npm --prefix dashboard ci
      - npm --prefix src/renderer ci
  
  build:
    command:
      - npm run build:backend
      - npm run build:frontend
      - npm run build:electron

  publish:
    command:
      - npm run make
      - npm run publish
      
  start:
    command:
      - npm run build:electron
      - npm run start
