# This is a taskctl's tasks configuration file.
# More information at https://github.com/taskctl/taskctl
pipelines:
  start:
    - task: install
    - task: build
      depends_on: install
    - task: start
      depends_on: build
  
  publish:
    - task: install
    - task: build
      depends_on: install
    - task: publish
      depends_on: build
  
tasks:
  install:
    command:
      - npm --prefix apps/electron install
      - npm --prefix apps/renderer ci --ignore-scripts
  
  build:
    command:
      - npm run --prefix apps/renderer version
      - npm run --prefix apps/renderer build:frontend
      - npm run --prefix apps/renderer build:backend
      - npm run --prefix apps/electron build

  publish:
    command:
      - npm run --prefix apps/electron make
      - npm run --prefix apps/electron publish
    env_file: .envrc
  
  start:
    command:
      - npm run --prefix apps/electron build
      - npm run --prefix apps/electron start

output: raw
